### ISSUE TITLE
Fetch error on firefox and safari

### ISSUE THREAD

**Issue by Hacksore** [maxdemaio/chess-heat#74]
Issue from discord

https://discord.com/channels/796594544980000808/837800765602005051/1196159784555135098

tldr you can't set the user agent header for fetch, it's illegal I think.

**Comment by maxdemaio** [comment]
I think it also fails for Safari since it didn't work on my phone. I think I tried adding the agent header since Chess.com specified I needed it in their docs. But, if this doesn't work across browsers I might remove until I figure out another work around 👁️.

 https://www.chess.com/announcements/view/breaking-change-user-agent-contact-info-required

**Comment by Hacksore** [comment]
# 🫶🫶
